crawler/urls.py
from crawler import views
from django.urls import path, include

app_name = 'crawler'

urlpatterns = [
    path('dashboard/', views.index, name='index'),
    path('crawler/', views.crawler_index, name='crawler_index'),
    path('report/', views.report, name='report'),
    path('update-notifications/', views.update_notifications, name='update_notifications'),
    path('update-notifications-base/', views.update_notifications_base, name='update_notifications_base'),
    path('update/', views.update, name='update'),
    path('read/', views.read, name='read'),
    path('result/', views.process, name='process'),
    path('test/', views.test, name='test'),
    path('calender/', views.calendar, name='calendar'),
    path('social-scrape-data/', views.social, name='social'),
    path('falcon-api/<str:keyword>/', views.api, name='api'),
    path('scheduler/', include('scheduler.urls'), name='scheduler'),
]

falcon/urls.py
"""
falcon URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static


def redirect_login(request):
    if not request.user.is_authenticated:
        return redirect('auth_login')
    else:
        return redirect('crawler:index')


urlpatterns = [
    path('', redirect_login),
    path(r'^jet/', include('jet.urls', 'jet')),
    path(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('get-proxy/', include('rotatingIP.urls')),
    path('', include('crawler.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawler/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from crawler.models import UserProfile, Notifications, Keyword, Category, Link, CrawledLinks, SocialMedia
from scheduler.models import ScrapedLink
from django.contrib import messages
from utils.crawler_spider import crawling, count_items, wiki_data, wiki_scraping, social_media_scrape, extract_image, create_predict_image
from utils.news import news
from utils.analytics import category_percent, category_count, keyword_trends
from utils.image_processing import category_predict
import random, copy, json
from django.http import JsonResponse
from crawler.tasks import save_models, scrape_social
from django.db.models import Count


@login_required
def index(request):
    """

    :param request:
    :return: Home Page
    """
    userprofile = UserProfile.objects.get_or_create(user=request.user)[0]
    category = Category.objects.all()
    notifications = Notifications.objects.filter(user=userprofile).order_by('-pub_date')

    unread = notifications.filter(read=False)

    user_crawled_links = CrawledLinks.objects.filter(userprofile=userprofile).order_by('-pub_date')

    context = dict()
    context['home'] = True
    context['category'] = category
    context['userprofile'] = userprofile
    context['notifications'] = notifications[:5]
    context['unread_count'] = len(unread)
    context['user_crawler'] = user_crawled_links[:userprofile.recent_link]
    context['cat_percent'] = category_percent(request.user)

    return render(request, "crawler/index.html", context=context)




@login_required
def crawler_index(request):
    """

    :param request:
    :return: Crawler Page
    """
    context = dict()
    userprofile = UserProfile.objects.get(user=request.user)
    notifications = Notifications.objects.filter(user=userprofile).order_by('-pub_date')
    unread = notifications.filter(read=False)
    categories = [i.name for i in Category.objects.all()]
    crawled_links = CrawledLinks.objects.order_by('-pub_date')

    unique_keyword = list(crawled_links.filter(userprofile=userprofile).order_by().values_list('link__keyword__name', flat=True).distinct())

    copy_keyword = copy.copy(unique_keyword)
    random.shuffle(copy_keyword)

    keywords_labels, keywords_dataset = keyword_trends(copy_keyword[1:6])

    print(category_count(request.user))
    context['crawler_home'] = True
    context['userprofile'] = userprofile
    context['notifications'] = notifications[:5]
    context['unread_count'] = len(unread)
    context['crawled_links'] = crawled_links
    context['categories'] = categories
    context['category_data'] = category_count(request.user)
    context['unique_keyword'] = unique_keyword
    context['keywords_labels'] = keywords_labels
    context['keywords_dataset'] = keywords_dataset

    return render(request, "crawler/crawler.html", context=context)


@login_required
def report(request):
    """

    :param request:
    :return: Detailed Report
    """
    context = dict()
    render_dict = dict()
    temp = dict()
    category = Category.objects.all()
    userprofile = UserProfile.objects.get(user=request.user)
    notifications = Notifications.objects.filter(user=userprofile).order_by('-pub_date')

    unread = notifications.filter(read=False)

    crawled_links = CrawledLinks.objects.filter(userprofile=userprofile).order_by('pub_date')
    categories = [i.name for i in Category.objects.all()]
    unique_keywords = list(crawled_links.values_list('link__keyword__name', flat=True).distinct())

    for keyword in unique_keywords:
        for category in categories:
            temp[category] = CrawledLinks.objects.filter(userprofile=userprofile, link__keyword__name=keyword, link__category__name=category)
        context[keyword] = temp

    print(context)
    render_dict['report'] = True
    render_dict['category'] = category
    render_dict['userprofile'] = userprofile
    render_dict['notifications'] = notifications[:5]
    render_dict['unread_count'] = len(unread)
    render_dict['data'] = context
    return render(request, "crawler/report.html", context=render_dict)
    # return HttpResponse(context)

@login_required
def test(request):
    """

    :param request:
    :return: Beta Testing
    """
    userprofile = UserProfile.objects.get(user=request.user)
    context = dict()
    context['userprofile'] = userprofile
    return render(request, "crawler/result.html", context=context)

@login_required
def calendar(request):
    """

    :param request:
    :return: Home Page
    """
    userprofile = UserProfile.objects.get_or_create(user=request.user)[0]
    category = Category.objects.all()
    notifications = Notifications.objects.filter(user=userprofile).order_by('-pub_date')

    unread = notifications.filter(read=False)


    context = dict()
    context['calendar'] = True
    context['category'] = category
    context['userprofile'] = userprofile
    context['notifications'] = notifications[:5]
    context['unread_count'] = len(unread)


    return render(request, "crawler/calendar.html", context=context)


@login_required
def social(request):
    if request.method == 'POST':
        keyword = request.POST.get('keyword')
        # key = Keyword.objects.get(name=keyword)
        # scrape_data = SocialMedia.objects.filter(keyword=key)
        scrape_data = social_media_scrape(keyword)
        context = {
            'scrape_data': scrape_data
        }
        return render(None, 'crawler/social.html', context=context)


@login_required
def update(request):
    """

    :param request:
    :return: update profile settings
    """
    if request.method == 'POST':
        userprofile = UserProfile.objects.get(user=request.user)
        query = str(request.POST['query'])
        userprofile.concurrency = int(query)
        update_percent = (userprofile.concurrency / 10) * 100
        userprofile.save()

        content = "Concurrency updated successfully."
        notification = Notifications(user=userprofile, content=content)
        notification.save()

        messages.success(request, content, extra_tags='concurrent_update')
        new_notification = Notifications.objects.filter(user=userprofile, read=False)

        context = {
            'update': query,
            'update_percent': update_percent,
            'new_count': len(new_notification)
        }

        return render(request, 'crawler/update.html', context=context)


@login_required
def update_notifications(request):
    """

    :param request:
    :return: generate report Notifications
    """
    if request.method == 'POST':
        userprofile = UserProfile.objects.get(user=request.user)
        keyword = str(request.POST['keyword'])
        content = f"Report is being generated for '{keyword}'"
        notification = Notifications(user=userprofile, content=content)
        notification.save()

        return HttpResponse("1")


@login_required
def update_notifications_base(request):
    """

    :param request:
    :return: Notifications
    """
    if request.method == 'POST':
        userprofile = UserProfile.objects.get(user=request.user)
        notifications = Notifications.objects.filter(user=userprofile).order_by('-pub_date')

        context = {
            'notifications': notifications[:5]
        }

        return render(None, "crawler/update_notifications.html", context=context)


@login_required
def read(request):
    """

    :param request:
    :return: Notifcations read/unread
    """
    if request.method == 'POST':
        userprofile = UserProfile.objects.get(user=request.user)
        notifications = Notifications.objects.filter(user=userprofile)

        for notification in notifications:
            notification.read = True
            notification.save()

        return HttpResponse("0")


def api(request, keyword):
    """

    :param request:
    :param keyword:
    :return: Falcon Custom API
    """
    temp = dict()
    result = news(keyword)
    userprofile = UserProfile.objects.get(user=request.user)
    key = Keyword.objects.get(name=keyword)
    crawled_links = CrawledLinks.objects.filter(userprofile=userprofile, link__keyword=key)

    for link in crawled_links:
        temp[link.link.link] = link.link.scrape_data

    temp["summarized data"] = result
    data = {
        keyword: temp
    }
    return JsonResponse(data)


@login_required
def process(request):
    """

    :param request:
    :return: Result Page
    """
    if request.method == 'POST':

        userprofile = UserProfile.objects.get(user=request.user)
        notifications = Notifications.objects.filter(user=userprofile).order_by('-pub_date')
        unread = notifications.filter(read=False)

        main_search = request.POST.get('main_search')
        filters = request.POST['multiple_select']
        reschedule_crawler = request.POST.get('reschedule_crawler')
        print(type(main_search), type(filters))

        main_search_list = [x.strip(' ') for x in main_search.split(',')]
        filters_list = [x.strip(' ') for x in filters.split(',')]

        result1 = dict()
        result2 = dict()
        result3 = dict()
        result4 = dict()
        news_data1 = dict()
        news_data2 = dict()
        list1 = list()
        list2 = list()
        temp_list1 = list()
        wiki_links = list()
        video_links = list()
        pdfs = list()
        images = list()
        scrape_data = ""
        no_of_links = 0
        no_of_scrape = 0
        wiki_scrape_temp = dict()
        scrape_data_dict = dict()
        scrape_data_dict_main = dict()
        colors = ['#111', '#f59042', '#555644', '#444']

        # print(result1)

        print(filters_list)

        for keyword in main_search_list:
            query = Keyword.objects.get_or_create(name=keyword)[0]
            query.save()
            pipeline_result = crawling(keyword, filters_list)[2]

templates/crawler/calendar.html
{% extends 'crawler/base.html' %}
{% load static %}
{% load crawlerapp_filter %}

{% block title %} Calender{% endblock %}

{% block custom_style %}
<link href="{% static 'plugins/calendar/core/main.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/calendar/daygrid/main.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/calendar/timegrid/main.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/calendar/list/main.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/calendar/bootstrap/main.min.css' %}" rel="stylesheet" />
{% endblock %}


{% block body %}
<div class="calendar">

<div class="calendar-body">
<div id="calendar"></div>
</div>


<div class="calendar-sidebar">
<div class="desktop-sticky-top flex-fill">
<div class="calendar-sidebar-title">Draggable Events:</div>
<div class="fc-event-list" id="external-events">
<div class="fc-event-item"><div class="fc-event-link" data-color="#ff2d55"><i class="fa fa-circle fs-8px mr-2 text-pink"></i> Meeting</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#ff3b30"><i class="fa fa-circle fs-8px mr-2 text-danger"></i> Group Discussion</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#FF9500"><i class="fa fa-circle fs-8px mr-2 text-warning"></i> Brainstorming</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#FFCC00"><i class="fa fa-circle fs-8px mr-2 text-yellow"></i> Presentation</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#1ABD36"><i class="fa fa-circle fs-8px mr-2 text-success"></i> Holiday</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#0cd096"><i class="fa fa-circle fs-8px mr-2 text-teal"></i> Sick Leave</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#30beff"><i class="fa fa-circle fs-8px mr-2 text-info"></i> Overtime</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#1f6bff"><i class="fa fa-circle fs-8px mr-2 text-blue"></i> Work from Home</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#640DF3"><i class="fa fa-circle fs-8px mr-2 text-indigo"></i> Business Travel</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#5b2e91"><i class="fa fa-circle fs-8px mr-2 text-purple"></i> Breakfast</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#869ac0"><i class="fa fa-circle fs-8px mr-2 text-muted"></i> Lunch</div></div>
<div class="fc-event-item"><div class="fc-event-link" data-color="#869ac0"><i class="fa fa-circle fs-8px mr-2 text-muted"></i> Dinner</div></div>
</div>
</div>
</div>

</div>

{% endblock %}

{% block script %}
<script
  src="https://code.jquery.com/jquery-3.5.1.js"
  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="{% static 'js/app.min.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
<script src="{% static 'plugins/moment/moment.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
<script src="{% static 'plugins/calendar/core/main.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
<script src="{% static 'plugins/calendar/daygrid/main.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
<script src="{% static 'plugins/calendar/timegrid/main.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
<script src="{% static 'plugins/calendar/interaction/main.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
<script src="{% static 'plugins/calendar/list/main.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
<script src="{% static 'plugins/calendar/bootstrap/main.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
<script src="{% static 'js/demo/calendar.demo.js' %}" type="48d7d880bf1fa512cb1b4416-text/javascript"></script>
	<script>
			$('#notification-read').click(function(){
	$.ajax({
            url: "/read/",
            type: "POST",
            data: { 'status' : true, "csrfmiddlewaretoken" : $("input[name=csrfmiddlewaretoken]").val()},
            success: function(response){
					$('#unread-update').html(response);
            }

        });

        $.ajax({
            url: "/update-notifications-base/",
            type: "POST",
            data: { 'status' : true, "csrfmiddlewaretoken" : $("input[name=csrfmiddlewaretoken]").val()},
            success: function(response){
					$('#notification_area').html(response);
            }

        });

});


		</script>
{% endblock %}

templates/crawler/crawler.html
{% extends 'crawler/base.html' %}
{% load static %}
{% load crawlerapp_filter %}

{% block title %} Crawler {% endblock %}


{% block custom_style %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" />
<script
	  src="https://code.jquery.com/jquery-3.3.1.min.js"
	  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	  crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.json-viewer.js' %}"></script>
<link href="{% static 'css/jquery.json-viewer.css' %}" type="text/css" rel="stylesheet">
<style>
	/*
 *  STYLE 3
 */

#style-3::-webkit-scrollbar-track
{
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
	background-color: #F5F5F5;
}

#style-3::-webkit-scrollbar
{
	width: 6px;
	background-color: #F5F5F5;
}

#style-3::-webkit-scrollbar-thumb
{
	background-color: #000000;
}

.shadow{
	box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
	}

</style>

{% endblock %}


{% block body %}

<ul class="breadcrumb">
<li class="breadcrumb-item section-title"><a href="{% url 'crawler:index' %}">FALCON</a></li>
<li class="breadcrumb-item section-title active lang" key="crawler">CRAWLER</li>
</ul>


<div class="container">

    <div id="datatable" class="mb-5">
	<h4 style="font-family:'Montserrat'">CRAWLER</h4>
		<div class="row mb-4">
			<div class="col-md-3 ">
				<div class="card bg-light shadow  mt-4 p-3">
					<div class="card-body">
						<h5 class="card-title" style="font-family:'Montserrat'">{{ userprofile.user.username|title }},</h5>
						{% if userprofile.crawled_links %}
						<p class="card-text">you have crawled <span class="text-primary" style="font-family:'Montserrat'">{{ userprofile.crawled_links }}</span> links till now.</p>
						{% else %}
						<p class="card-text">you haven't <span class="text-primary" style="font-family:'Montserrat'">crawled </span> any links yet.</p>
						{% endif %}
						<p class="card-text"><small class="text-muted">with <span class="text-primary" style="font-family:'Montserrat'">{{ userprofile.time_spent_scraping }}</span> hours spent scraping.</small></p>
					  </div>
				  </div>
			</div>

				<canvas id="barChart" class="col-md-6" height="300"></canvas>

			<div class="col-md-3">
				<div class="card bg-secondary  mt-4 p-3 border-0 shadow">
					<div class="card-body" id="style-3" style="overflow-y:scroll; height:150px;">
						<h5 class="card-title text-white" style="font-family:'Montserrat'" > API's </h5>
						<hr>
						{% if unique_keyword %}
						{% for keyword in unique_keyword %}
						<p class="card-text"><a href="{% url 'crawler:api' keyword %}"  target="_blank" class="section-title btn btn-dark btn-sm">{{ keyword|upper }}</a></p>
						{% endfor %}
						{% else %}
						<p class="card-text">Crawl links get API's</p>
						{% endif %}
					  </div>
				  </div>
			</div>


		</div>

		<div class="row mb-4 justify-content-start">
			<div class="col-12">
				<button class="btn btn-dark btn-sm" data-toggle="modal" data-target="#keyword_trends" style="font-family:'Montserrat'">See Keyword Trend's</button>
			</div>
		</div>

	<div class="card border-0 shadow">
		<div class="card-body">
			<table id="datatableDefault" class="table table-sm table-borderless text-nowrap w-100">
				<thead class="thead-dark section-title">
					<tr>
						<th>#</th>
						<th>AUTHOR</th>
						<th>LINKS</th>
						<th>CATEGORY</th>
						<th>KEYWORD</th>
						<th>TIME</th>
					</tr>
				</thead>
				<tbody>
				{% for link in crawled_links %}
					<tr>
						<td>{{ forloop.counter }}</td>
						<td>{{ link.userprofile.user.username }}</td>
						<td data-toggle="popover" data-content="{{ link.link.link }}" data-trigger="hover" data-placement="left">
							<a href="#" data-toggle="modal" data-target="#modal_link_{{ forloop.counter }}">
								{{ link.link.link|truncatechars:30 }}
							</a>
						</td>
						<td>
							<i class="fa fa-circle fs-9px fa-fw text-{% if link.link.category.name|stringformat:'s' == 'crime' %}primary{% elif link.link.category.name|stringformat:'s' == 'child_abuse' %}danger{% elif link.link.category.name|stringformat:'s' == 'woman_abuse' %}warning{% else %}teal{% endif %} mr-2" data-toggle="popover" data-content="{{ link.link.category.name }}" data-trigger="hover" data-placement="left"></i>
							{{ link.link.category.name }}
						</td>
						<td>{{ link.link.keyword.name }}</td>
						<td data-toggle="popover" data-content="{{ link.pub_date }}" data-trigger="hover" data-placement="left"> {{ link.whenpublished }}</td>
					</tr>
				{% endfor %}

				</tbody>
			</table>
		</div>



</div>

{% endblock %}


{% block script %}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="{% static 'js/app.min.js' %}" type="59f984106ec2e39727363fa8-text/javascript"></script>
<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/chart.js/dist/Chart.min.js' %}" ></script>

<script>


  $(function() {

    $('#datatableDefault').DataTable({
    dom: "<'row mb-3'<'col-sm-4'l><'col-sm-8 text-right'<'d-flex justify-content-end'fB>>>t<'d-flex align-items-center'<'mr-auto'i><'mb-0'p>>",
    lengthMenu: [ 20, 30, 40, 50, 60 ],
    responsive: true,
    buttons: [
      { extend: 'print', className: 'btn btn-default' },
      { extend: 'csv', className: 'btn btn-default' }
    ]
  });


$('[data-toggle="popover"]').popover();

{% for link in crawled_links %}
	$('#json-renderer_{{ forloop.counter }}').jsonViewer({{ link.link.scrape_data|safe }});
{% endfor %}

});

</script>

<script>

var ctx = document.getElementById('barChart');

var barChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: {{ categories|safe }},
    datasets: [{
      label: '# of Links Crawled in each Category',
      data: {{ category_data| safe }},
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',

      ],
      borderColor: [
        'rgba(255,99,132,1)',
        'rgba(54, 162, 235, 1)',
        'rgba(255, 206, 86, 1)',
        'rgba(75, 192, 192, 1)',
        'rgba(153, 102, 255, 1)',

      ],
      borderWidth: 1
    },{
      label: '# of Links Crawled in each Category',
      data: {{ category_data| safe }},
      type: 'line',
      borderColor: "#649CFF",
      fill: false
    }


    ]
  },
  options: {
    responsive: true,

  }
});
</script>

		<script>
			$('#notification-read').click(function(){
	$.ajax({
            url: "/read/",
            type: "POST",
            data: { 'status' : true, "csrfmiddlewaretoken" : $("input[name=csrfmiddlewaretoken]").val()},
            success: function(response){
					$('#unread-update').html(response);
            }

        });

        $.ajax({
            url: "/update-notifications-base/",
            type: "POST",
            data: { 'status' : true, "csrfmiddlewaretoken" : $("input[name=csrfmiddlewaretoken]").val()},
            success: function(response){
					$('#notification_area').html(response);
            }

        });

});


		</script>


		<script>
new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: {{ keywords_labels|safe }},
    datasets: [
    {% for key, value in keywords_dataset.items %}
    {
        data: {{ value.0|safe }},
        label: "{{ key }}",
        borderColor: "{{ value.1|safe }}",
        fill: false
      },
       {% endfor %}

    ]
  },
  options: {
    title: {
      display: true,
      text: 'Keyword searched time interest'
    },
  }
});
		</script>

{% endblock %}

templates/crawler/update.html
<h3 class="text-white mt-n1">{{ update }} workers</h3>
<div class="progress bg-black-transparent-5 mb-2" style="height: 6px">
    <div class="progrss-bar progress-bar-striped bg-white" style="width: {{ update_percent }}%"></div>
</div>

<input type="hidden" value="{{ new_count }}" id="new_count">



<!--	notifications  -->
	{% if messages %}<div class="toasts-container">

	{% for message in messages %}

		<div class="toast fade hide" data-autohide="true" id="concurrent_toast">
		  <div class="toast-header">
			<i class="far fa-bell text-muted mr-2"></i>
			<strong class="mr-auto">Concurrency</strong>
			<small>1 sec ago</small>
			<button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
			  <span>×</span>
			</button>
		  </div>
		  <div class="toast-body">
			{{ message }}
		  </div>
		</div>

	{% endfor %}
    </div>
	{% endif %}

templates/crawler/update_notifications.html
<h6 class="dropdown-header text-gray-900 mb-1">Notifications</h6>
						{% for notification in notifications %}
						<a href="#" class="dropdown-notification-item">
							<div class="dropdown-notification-icon">
<i class="fa fa-receipt fa-lg fa-fw text-success"></i>
							</div>
							<div class="dropdown-notification-info">
								<div class="title">{{ notification.content }}</div>
								<div class="time">{{ notification.whenpublished }}</div>
							</div>
							<div class="dropdown-notification-arrow">
<i class="fa fa-chevron-right"></i>
							</div>
						</a>
						{% endfor %}

						<div class="p-2 text-center mb-n1">
<a href="#" class="text-gray-800 text-decoration-none">See all</a>
						</div>